### ISSUE TITLE
Bug: Migrator config unnecessarily calls fixupConfigRules and fixupPluginRules on typescript-eslint

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [eslint/rewrite#100]
### Which packages are affected?

- [ ] `@eslint/compat`
- [ ] `@eslint/config-array`
- [ ] `@eslint/core`
- [X] `@eslint/migrate-config`
- [ ] `@eslint/object-schema`

### Environment

Node version: 22.4.1
npm version: n/a
ESLint version: 9.x
Operating System: n/a

### What did you do?

```shell
git clone https://github.com/MariuzM/expo-starter
cd expo-starter
npx @eslint/migrate-config .eslintrc
```

### What did you expect to happen?

The generated config should only call `fixupConfigRules` and `fixupPluginRules` on configs/plugins that need it. As of [typescript-eslint releasing 8.0.0](https://typescript-eslint.io/blog/announcing-typescript-eslint-v8), that's no longer typescript-eslint.

For example, from the sample linked repo:

```js
import { fixupConfigRules } from '@eslint/compat';
import typescriptEslint from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import js from '@eslint/js';
import { FlatCompat } from '@eslint/eslintrc';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
  allConfig: js.configs.all,
});

export default [
  {
    ignores: [
      // ...
    ],
  },
  ...fixupConfigRules(
    compat.extends(
      'plugin:react-hooks/recommended',
      'plugin:import/recommended',
      'plugin:import/typescript'
    )
  ),
  ...tseslint.configs.recommended,
  {
    settings: {
      'import/ignore': ['react-native'],
    },

    rules: {
      // ...
    },
  },
];
```

### What actually happened?

`typescript-eslint` packages are stilled wrapped in the fixup functions.

```js
import { fixupConfigRules, fixupPluginRules } from '@eslint/compat';
import typescriptEslint from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import js from '@eslint/js';
import { FlatCompat } from '@eslint/eslintrc';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
  allConfig: js.configs.all,
});

export default [
  {
    ignores: [
      // ...
    ],
  },
  ...fixupConfigRules(
    compat.extends(
      'plugin:@typescript-eslint/recommended',
      'plugin:react-hooks/recommended',
      'plugin:import/recommended',
      'plugin:import/typescript'
    )
  ),
  {
    plugins: {
      '@typescript-eslint': fixupPluginRules(typescriptEslint),
    },

    languageOptions: {
      parser: tsParser,
    },

    settings: {
      'import/ignore': ['react-native'],
    },

    rules: {
      // ...
    },
  },
];
```

### Link to Minimal Reproducible Example

https://github.com/MariuzM/expo-starter

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

I'm a little pressed for time right now, so omitting the minimum repro because I think this is a fairly straightforward request. I can take the time to make one if you really need. 🙂

**Comment by nzakas** [comment]
This isn't technically a bug because this was needed, but since things have changed, we can update the tool.

**Comment by nzakas** [comment]
So I took a look at this and it's not a bug, it's working as intended.

The issue is that the config is using `extends` with some configs that still require `fixupConfigRules()`:

```js
    compat.extends(
      'plugin:@typescript-eslint/recommended',
      'plugin:react-hooks/recommended',    // requires fixupConfigRules()
      'plugin:import/recommended',    // requires fixupConfigRules()
      'plugin:import/typescript'    // requires fixupConfigRules()
    )
```

Because it's referenced in the same `extends`, `typescript-eslint` is also being wrapped by `fixupConfigRules()`. As a result, the `typescript-eslint` plugin object that is added behind the scenes would be different than the one directly from the import. To fix that, `typescript-eslint` must be passed through `fixupPluginRules()` in order to have the same object in both places.

So if this config stops using configs that require `fixupConfigRules()`, `typescript-eslint` will no longer be wrapped in `fixupPluginRules()`.

As-is, this doesn't cause any change in functionality.
