### ISSUE TITLE
Change Request: Add @types/eslint dependency

### ISSUE THREAD

**Issue by danielrentz** [eslint/rewrite#105]
### Which packages would you like to change?

- [X] `@eslint/compat`
- [ ] `@eslint/config-array`
- [ ] `@eslint/core`
- [ ] `@eslint/migrate-config`
- [ ] `@eslint/object-schema`

### What problem do you want to solve?

Prevent type errors when using this plugin in TS files. Follow up from #104.

### What do you think is the correct solution?

This package exports type definitions in d.ts files referencing types from the `eslint` package. Therefore, it should include `@types/eslint` as public dependency.

As stated in #104, this package should work with `@types/eslint` v8 and v9, therefore the dependency should be just `"*"` as done in <https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/eslint__js/package.json#L9>

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Let's keep the conversation on https://github.com/eslint/rewrite/issues/104. There's no need for a separate issue.
