### ISSUE TITLE
Change Request: Set up Renovate

### ISSUE THREAD

**Issue by nzakas** [eslint/rewrite#30]
### Which packages would you like to change?

- [ ] `@eslint/compat`
- [ ] `@eslint/config-array`
- [ ] `@eslint/object-schema`

### What problem do you want to solve?

We currently don't have any automated dependency updates in this repo.

### What do you think is the correct solution?

We should set up Renovate, but before doing that, we should copy over the config file we use in `eslint/eslint` to ensure we don't get hammered with updates.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by harish-sethuraman** [comment]
will pick this
