### ISSUE TITLE
Change Request: Utility function to read gitignore files

### ISSUE THREAD

**Issue by nzakas** [eslint/rewrite#44]
### Which packages would you like to change?

- [X] `@eslint/compat`
- [ ] `@eslint/config-array`
- [ ] `@eslint/migrate-config`
- [ ] `@eslint/object-schema`

### What problem do you want to solve?

In v8, people pass `--ignore-path .gitignore` in order to use `.gitignore` patterns with ESLint.

In v9, there is no obvious way to use the `.gitignore` patterns in an `eslint.config.js` file, leaving people confused.

### What do you think is the correct solution?

1. Copy the [conversion function](https://github.com/eslint/rewrite/blob/5435aaba4909564af28d326a84fba7e9f643bd58/packages/migrate-config/src/migrate-config.js#L129-L152) from `migrate-config` into `compat` and export it, making it available to end users.
2. Export an `includeIgnoreFile()` function that reads in an ignore file and automatically converts into the format that the config file needs, such that we can do this:

```js
export default [
    await includeIgnoreFile(".gitignore", __dirname),

    // other configs here

];
```

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by mdjermanovic** [comment]
Makes sense to me, marked as accepted.

> ```js
> await includeIgnoreFile(".gitignore", __dirname),
> ```

I'm wondering if this function needs to be async, as that would make the use of it complicated in CommonJS config files.

**Comment by nzakas** [comment]
I suppose we could do it synchronously.

**Comment by nzakas** [comment]
Working on this.

**Comment by wong2** [comment]
How about reading multiple `.gitignore` files? I have a monorepo where each package has its own .gitignore file.
