### ISSUE TITLE
Bug: (Unable to resolve path to module '@eslint/compat.'.eslintimport/no-unresolved)

### ISSUE THREAD

**Issue by zapzqc** [eslint/rewrite#46]
### Which packages are affected?

- [X] `@eslint/compat`
- [ ] `@eslint/config-array`
- [ ] `@eslint/migrate-config`
- [ ] `@eslint/object-schema`

### Environment

Node version: v18.20.3
pnpm version: 9.1.4
ESLint version: 9.4.0
Operating System: MacOS 11.5.2
VS Code

### What did you do?

My project is written in JavaScript, and I would like to add ESLint to it.

### What did you expect to happen?

`import { fixupConfigRules } from '@eslint/compat';`
This line should not be prompted with an error

### What actually happened?

Unable to resolve path to module '@eslint/compat.'.eslint[import/no-unresolved](https://github.com/import-js/eslint-plugin-import/blob/v2.29.1/docs/rules/no-unresolved.md)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/vitejs-vite-bm5pcp

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

<img width="908" alt="image" src="https://github.com/eslint/rewrite/assets/3996569/c61683eb-841a-430b-a2d6-25a98d8cb483">

When I added "main": "./dist/esm/index.js" to the package.json file under the node_modules/@eslint/compact directory, my editor stopped showing errors.

**Comment by Rec0iL99** [comment]
Hi @zapzqc, thanks for the issue. I think this is related to the `import/no-unresolved` rule coming from the [`eslint-plugin-import`](https://github.com/import-js/eslint-plugin-import) plugin and not something we can solve. Please get in touch with the maintainers there.

**Comment by nzakas** [comment]
The reproduction case you linked to does not show this error. Please provide a repro case where we can see the error in action and we can take a look.

**Comment by Rec0iL99** [comment]
> The reproduction case you linked to does not show this error. Please provide a repro case where we can see the error in action and we can take a look.

Hi @nzakas, I could reproduce this. This is related to the `no-unresolved`  rule from `eslint-plugin-import`, but I'm not sure if it is because `@eslint/compat` does not have a `main` property in its `package.json`. The rule does not complain when there is a `main` property.

```bash
npx eslint .

/home/projects/vitejs-vite-bm5pcp/eslint.config.js
   3:34  error  Unable to resolve path to module '@eslint/compat'  import/no-unresolved
```

**Comment by nzakas** [comment]
Oh I see. There were no instructions on how to use the StackBlitz repro. I thought from the description that the error shows up immediately upon opening it. I didn't realize I had to manually run ESLint.

This seems more like a bug in `eslint-plugin-import` to me, but if adding `main` unblocks people, we can do that.

**Comment by nzakas** [comment]
Just a note that we should do this for all the packages, not just `@eslint/compat`.
