### ISSUE TITLE
Change Request: Remove `ConfigArray#isExplicitMatch()`

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/rewrite#51]
### Which packages would you like to change?

- [ ] `@eslint/compat`
- [X] `@eslint/config-array`
- [ ] `@eslint/migrate-config`
- [ ] `@eslint/object-schema`

### What problem do you want to solve?

`ConfigArray#isExplicitMatch()` is out of sync with the rest of the logic of config-array, and we're not using this method in ESLint anymore.

### What do you think is the correct solution?

Remove `ConfigArray#isExplicitMatch()` method.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
Makes sense to me. There's a bunch of other logic I think we can remove now, too, specifically around including functions and arrays in the array. We're not using those features, so I don't think it makes sense to leave them in at this point.
