### ISSUE TITLE
Docs: Add sponsors to each README

### ISSUE THREAD

**Issue by nzakas** [eslint/rewrite#54]
### Docs page(s)

packages/compat/README.md
packages/migrate-config/README.md
packages/object-schema/README.md
packages/config-array/README.md

### What documentation issue do you want to solve?

We aren't displaying sponsors on any of our READMEs.

### What do you think is the correct solution?

Automatically update the sponsors list every day like we do in `eslint/eslint`.

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by harish-sethuraman** [comment]
I'll pick this

**Comment by nzakas** [comment]
That's correct.
