### ISSUE TITLE
Change Request: Set up typescript-eslint

### ISSUE THREAD

**Issue by nzakas** [eslint/rewrite#69]
### Which packages would you like to change?

- [X] `@eslint/compat`
- [X] `@eslint/config-array`
- [ ] `@eslint/migrate-config`
- [X] `@eslint/object-schema`

### What problem do you want to solve?

We have several packages that have at least one `.ts` file, but we have no automation aside from running `tsc` to check its validity.

### What do you think is the correct solution?

We should set up typescript-eslint to lint all `.ts` files. This will double as an integration test for us with typescript-eslint.

### Participation

- [ ] I am willing to submit a pull request for this change.

### Additional comments

@JoshuaKGoldberg feel like taking this one?

**Comment by JoshuaKGoldberg** [comment]
I'd love to. 🙂

**Comment by JoshuaKGoldberg** [comment]
I think I should wait until #68 is in.
