### ISSUE TITLE
Change Request: Publish packages with provenance

### ISSUE THREAD

**Issue by nzakas** [eslint/rewrite#76]
### Which packages would you like to change?

- [X] `@eslint/compat`
- [X] `@eslint/config-array`
- [X] `@eslint/core`
- [X] `@eslint/migrate-config`
- [X] `@eslint/object-schema`

### What problem do you want to solve?

Our packages are not being published with provenance on npm (JSR automatically has provenance enabled).

### What do you think is the correct solution?

Set up `release-please` to generate provenance for each package.

https://docs.npmjs.com/generating-provenance-statements?ref=blog.lsantos.dev#example-github-actions-workflow

### Participation

- [ ] I am willing to submit a pull request for this change.

**Comment by amareshsm** [comment]
I haven't worked with prevenance before, but I'd like to give it a try.

**Comment by nzakas** [comment]
Go ahead and give it a try. :+1:

**Comment by mdjermanovic** [comment]
@amareshsm are you still working on this? I think all that needs to be done is to add the `--provenance` flag to `npm publish` commands.

**Comment by mdjermanovic** [comment]
Fixed by https://github.com/eslint/rewrite/pull/86.
