### ISSUE TITLE
[Windows] Bug: npm ENOENT in `%APPDATA%/npm`

### ISSUE THREAD

**Issue by glenn2223** [eslint/rewrite#88]
### Which packages are affected?

- [ ] `@eslint/compat`
- [ ] `@eslint/config-array`
- [ ] `@eslint/core`
- [X] `@eslint/migrate-config`
- [ ] `@eslint/object-schema`

### Environment

Node version: 22.4.1
npm version: 10.8.1
ESLint version: 10.4.5 AND 11.0.0
Operating System: Windows 11 (Windows_NT 10.0.22631) plus my other local Windows 11 PC

### What did you do?

First, I hope this is the right place to open this issue. This is the only `npx` command I've had issue with recently so I assume it's nothing I've done wrong 😁

### What I did

Migrating my `.eslintrc.json` file using `npx @eslint/migrate-config ".eslintrc.json"`

### What did you expect to happen?

The command to run successfully

### What actually happened?

I have npm installed at `C:\Program Files\nodejs` and there's nothing in my AppData folder.

```diff
PS G:\MyPath> npx @eslint/migrate-config ".eslintrc.json"
npm error code ENOENT
npm error syscall lstat
npm error path C:\Users\MyUser\AppData\Roaming\npm
npm error errno -4058
npm error enoent ENOENT: no such file or directory, lstat 'C:\Users\MyUser\AppData\Roaming\npm'
npm error enoent This is related to npm not being able to find a file.
npm error enoent
npm error A complete log of this run can be found in: C:\Users\MyUser\AppData\Local\npm-cache\_logs\2024-07-17T12_50_57_438Z-debug-0.log
```

See workaround and details below 👇

### Link to Minimal Reproducible Example

N/A

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Additional comments

Details taken from the log file

```diff
0 verbose cli C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js
1 info using npm@10.8.1
2 info using node@v22.4.1
3 silly config load:file:C:\Program Files\nodejs\node_modules\npm\npmrc
4 silly config load:file:G:\MyPath\.npmrc
5 silly config load:file:C:\Users\MyUser\.npmrc
6 silly config load:file:C:\Users\MyUser\AppData\Roaming\npm\etc\npmrc
7 verbose title npm exec @eslint/migrate-config .eslintrc.json
8 verbose argv "exec" "--" "@eslint/migrate-config" ".eslintrc.json"
9 verbose logfile logs-max:10 dir:C:\Users\MyUser\AppData\Local\npm-cache\_logs\2024-07-17T12_50_57_438Z-
10 verbose logfile C:\Users\MyUser\AppData\Local\npm-cache\_logs\2024-07-17T12_50_57_438Z-debug-0.log
11 silly logfile start cleaning logs, removing 1 files
12 silly logfile done cleaning log files
13 silly packumentCache heap:4345298944 maxSize:1086324736 maxEntrySize:543162368
14 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules/@topmarksdevelopment/hover-box
15 http fetch GET 200 https://registry.npmjs.org/@eslint%2fmigrate-config 560ms (cache miss)
16 silly packumentCache heap:4345298944 maxSize:1086324736 maxEntrySize:543162368
17 verbose stack Error: ENOENT: no such file or directory, lstat 'C:\Users\MyUser\AppData\Roaming\npm'
17 verbose stack     at async lstat (node:internal/fs/promises:1024:18)
17 verbose stack     at async #loadActual (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\load-actual.js:112:20)
17 verbose stack     at async exec (C:\Program Files\nodejs\node_modules\npm\node_modules\libnpmexec\lib\index.js:203:26)
17 verbose stack     at async Npm.exec (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:207:9)
17 verbose stack     at async module.exports (C:\Program Files\nodejs\node_modules\npm\lib\cli\entry.js:74:5)
18 error code ENOENT
19 error syscall lstat
20 error path C:\Users\MyUser\AppData\Roaming\npm
21 error errno -4058
22 error enoent ENOENT: no such file or directory, lstat 'C:\Users\MyUser\AppData\Roaming\npm'
23 error enoent This is related to npm not being able to find a file.
23 error enoent
24 verbose cwd G:\MyPath
25 verbose os Windows_NT 10.0.22631
26 verbose node v22.4.1
27 verbose npm  v10.8.1
28 verbose exit -4058
29 verbose code -4058
30 error A complete log of this run can be found in: C:\Users\MyUser\AppData\Local\npm-cache\_logs\2024-07-17T12_50_57_438Z-debug-0.log
```

### Workaround

I have npm installed at `C:\Program Files\nodejs` and no npm folder at `%AppData%` (or `C:\Users\MyUser\AppData\Roaming`).

I managed to get around the issue by creating the npm folder and adding 2 shortcuts for `npm` and `npx` that link to the files in  `C:\Program Files\nodejs`. To do this: have both files selected in `nodejs` folder, hold down your alt mouse button (usually right), drag it over to the new `npm` folder and release, then select "create shortcuts here" and rename them to `npm` and `npx` (remove the `.ps1 - Shortcut`)

With these shortcuts in place I could run the command without issue as below

```diff
PS G:\MyPath> npx @eslint/migrate-config ".eslintrc.json"
Need to install the following packages:
@eslint/migrate-config@1.1.2
Ok to proceed? (y) y


Migrating .eslintrc.json

Wrote new config to ./eslint.config.mjs

You will need to install the following packages to use the new config:


You can install them using the following command:

npm install  -D
```

P.s. it also seems you're outputting an install message even when nothing is required 😁

**Comment by nzakas** [comment]
This is directly related to your installation of Node.js/npm and not with the package itself. 

Another way to use the tool is just to install it globally and run from there:

```shell
npm install @eslint/migrate-config -g
@eslint/migrate-config .eslintrc.json
```
