### ISSUE TITLE
Change Request: CommonJS types for `@eslint/core`

### ISSUE THREAD

**Issue by fasttime** [eslint/rewrite#95]
### Which packages would you like to change?

- [ ] `@eslint/compat`
- [ ] `@eslint/config-array`
- [X] `@eslint/core`
- [ ] `@eslint/migrate-config`
- [ ] `@eslint/object-schema`

### What problem do you want to solve?

As per [this decision of 2024-06-27](https://github.com/eslint/rewrite/blob/main/decisions/004-types.md), type definitions from `@eslint/core` should be used in `@types/eslint` where possible. A challenge I encountered in my attempt to update `@types/eslint` is that it uses CommonJS syntax (this probably makes sense, because `eslint` itself is a CommonJS package). `@eslint/core` on the other hand only distributes ESM types, which makes it impossible to `import` those types in CommonJS out of the box. JSDoc style type imports like `/** @typedef {import("@eslint/core").SomeType} SomeType */` don't seems to work in TypeScript files.

### What do you think is the correct solution?

Add a CommonJS export to `@eslint/core` like for other packages in this repo.

### Participation

- [X] I am willing to submit a pull request for this change.

**Comment by nzakas** [comment]
> @eslint/core on the other hand only distributes ESM type

The types we export aren't ESM-specific. I've been using them in the [core](https://github.com/eslint/eslint/blob/f9ac978de629c9a702febcf478a743c5ab11fcf6/lib/linter/linter.js#L75-L77) without any problem.

Can you describe what problem you're seeing, maybe with a simple repro?

**Comment by fasttime** [comment]
I think that JSDoc comments don't work in TypeScript files. Here is a StackBlitz example that shows the issue:

https://stackblitz.com/edit/vitejs-vite-kgfgem?file=test.ts

Only the type imported with TypeScript syntax in recognized. The type declared in the comment produces a compile-time error.

DefinitelyType uses [a rule](https://github.com/gajus/eslint-plugin-jsdoc/blob/main/docs/rules/check-tag-names.md#repos-sticky-header) that prevents `@typedef` tags in JSDoc comments.

**Comment by nzakas** [comment]
Okay, but I'm not sure what that has to do with CommonJS types vs. ESM types. That seems more like something specific to `.ts` files. I can't imagine why you'd use JSDoc typedefs in a `.ts` file.

The StackBlitz is a module project using TypeScript with modules, so I'm unclear on how this relates to CommonJS.

**Comment by fasttime** [comment]
@nzakas I've added a `.cts` file to the StackBlitz project to show the error when an ESM module is imported: https://stackblitz.com/edit/vitejs-vite-kgfgem?file=test.cts

It seems that the error can be avoided using the budler module resolution in the TypeScript compiler option, i.e. setting `"module": "ESNext"` and `"moduleResolution": "bundler"` in `tsconfig.json`. However, we can't enforce those options for consumers of `@eslint/core`, so I think the best choice is still to add type declarations in CommonJS format. Those could be identical to what we are already exporting, we would just need to copy them to a `.cts` file.

**Comment by nzakas** [comment]
Ah okay, for the benefit of others, here's the error message:

```
The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@eslint/core")' call instead.
```

Makes sense to add a `.cts` file, but let's make sure that's created during the build process so we don't have to maintain two files.

Marking as accepted.

**Comment by fasttime** [comment]
I'll work on this.
